name: ci
on:
  push:
    paths-ignore:
      - "bin/**"
      - "docs/**"
      - "images/**"
      - ".editorconfig"
      - ".gitignore"
      - "CHANGELOG.md"
      - "CITATION.md"
      - "CONTRIBUTING.md"
      - "license.txt"
      - "README.md"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: git config --global --add safe.directory /__w/re-frame/re-frame

      - name: Maven cache
        id: maven-cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/project.clj', '.github/workflows/**') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('project.clj') }}-${{ hashFiles('**/deps.cljs') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: shadow-cljs compiler cache
        uses: actions/cache@v4
        with:
          path: .shadow-cljs
          key: ${{ runner.os }}-shadow-cljs-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-shadow-cljs-

      - uses: browser-actions/setup-chrome@v1
        id: setup-chrome
        with:
          chrome-version: 811961

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli:  'latest'
          bb:   'latest'

      - run: bb test :chrome-path '"${{ steps.setup-chrome.outputs.chrome-path }}"'

      - name: Test simple example
        working-directory: examples/simple
        run: |
          npm install
          npm run release

      - name: Test todomvc example
        working-directory: examples/todomvc
        run: |
          npm install
          npm run release

      - name: Verify cljdoc Configuration
        run: curl -fsSL https://raw.githubusercontent.com/cljdoc/cljdoc/master/script/verify-cljdoc-edn | bash -s docs/cljdoc.edn

      - name: Slack notification
        uses: homoluctus/slatify@v2.0.1
        if: failure() || cancelled()
        with:
          type: ${{ job.status }}
          job_name: re-frame Tests
          channel: '#oss-robots'
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
