name: cd
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - run: git config --global --add safe.directory /__w/re-frame/re-frame

      - name: Maven cache
        id: maven-cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/project.clj', '.github/workflows/**') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('project.clj') }}-${{ hashFiles('**/deps.cljs') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: shadow-cljs compiler cache
        uses: actions/cache@v4
        with:
          path: .shadow-cljs
          key: ${{ runner.os }}-shadow-cljs-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-shadow-cljs-

      - name: Test todomvc example
        working-directory: examples/todomvc
        run: |
          npm install
          npm run release

      - name: Test simple example
        working-directory: examples/simple
        run: |
          npm install
          npm run release

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli:  'latest'
          bb:   'latest'

      - run: bb test

      - name: Slack notification
        uses: homoluctus/slatify@v2.0.1
        if: failure() || cancelled()
        with:
          type: ${{ job.status }}
          job_name: re-frame Tests
          channel: '#oss-robots'
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Release
    needs: test
    runs-on: ubuntu-latest
    container:
      # Source: https://github.com/day8/dockerfiles-for-dev-ci-images
      image: ghcr.io/day8/chrome-56:5.0.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - run: git config --global --add safe.directory /__w/re-frame/re-frame

      - name: Maven cache
        id: maven-cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/project.clj', '.github/workflows/**') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '24'
            
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli:  'latest'
          bb:   'latest'

      - run: bb clojars
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_TOKEN: ${{ secrets.CLOJARS_TOKEN }}
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # This creates a 'GitHub Release' from the tag and includes link to the releases page
      # on the re-frame website. We do not use draft or prerelease features as we always want
      # the latest release to show in the right hand column of the project page regardless
      # of if it is a stable release.
      #
      # IMPORTANT: The release year is hard-coded and must be updated in this file once per year for the moment.
      # Unfortunately I could not find a way to inject the year using the GitHub Actions ${{ expr }} syntax.
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            [Changelog](http://day8.github.io/re-frame/releases/2025/)
          draft: false
          prerelease: false

      - name: Slack notification
        uses: homoluctus/slatify@v2.0.1
        if: always()
        with:
          type: ${{ job.status }}
          job_name: re-frame Deployment
          channel: '#oss-robots'
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
